/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    TrailMixManager: {
      address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "contractAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "ContractDeployed",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_erc20Token",
              type: "address",
            },
            {
              internalType: "address",
              name: "_stablecoin",
              type: "address",
            },
            {
              internalType: "address",
              name: "_priceFeed",
              type: "address",
            },
            {
              internalType: "address",
              name: "_uniswapRouter",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_trailAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_granularity",
              type: "uint256",
            },
          ],
          name: "deployTrailMix",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getUserContracts",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "userContracts",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
    },
  },
  80001: {
    TrailMixManager: {
      address: "0xFC570749B3DBAE786506c09b2Dd8bCE63c0dEede",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "contractAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "ContractDeployed",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_erc20Token",
              type: "address",
            },
            {
              internalType: "address",
              name: "_stablecoin",
              type: "address",
            },
            {
              internalType: "address",
              name: "_priceFeed",
              type: "address",
            },
            {
              internalType: "address",
              name: "_uniswapRouter",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_trailAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_granularity",
              type: "uint256",
            },
          ],
          name: "deployTrailMix",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getUserContracts",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "userContracts",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
    },
  },
  11155111: {
    TrailMixManager: {
      address: "0x871d9adBc69c200802A2FC645598045840c3c63F",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "contractAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "ContractDeployed",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_erc20Token",
              type: "address",
            },
            {
              internalType: "address",
              name: "_stablecoin",
              type: "address",
            },
            {
              internalType: "address",
              name: "_priceFeed",
              type: "address",
            },
            {
              internalType: "address",
              name: "_uniswapRouter",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_trailAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_granularity",
              type: "uint256",
            },
          ],
          name: "deployTrailMix",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getUserContracts",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "userContracts",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
